version: '3.8'
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
      - VERSION=docker
    volumes:
      - ./config:/config
      - /path/to/Serier:/Serier
      - /path/to/Filmer:/Filmer
      - /path/to/Musikk:/Musikk
      - /path/to/Konserter:/Konserter
      - /path/to/Videoer:/Videoer
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
  tautulli:
    image: tautulli/tautulli:latest
    container_name: tautulli
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - ./tautulli-config:/config
    restart: unless-stopped
